In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification

In [2]:
X,y = make_classification(n_samples=2000,n_features=4,n_classes=2,random_state=0)

In [3]:
X.shape

(2000, 4)

In [4]:
X

array([[-0.21328819,  0.65425764,  0.92983206,  0.00313137],
       [-1.69655301, -1.4305697 ,  0.93600596,  0.34480654],
       [ 0.31414742,  1.30909882,  0.84340826, -0.11419435],
       ...,
       [-1.11455053, -1.37786766,  0.1883809 ,  0.24764188],
       [-1.13571347, -0.94061429,  0.64318002,  0.23000004],
       [-1.3451129 , -1.11997136,  0.75599421,  0.27269265]])

In [5]:
y

array([1, 0, 1, ..., 0, 0, 0])

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [8]:
X_train.shape

(1600, 4)

In [9]:
X_test.shape

(400, 4)

In [10]:
from keras.models import Sequential
from keras.layers import Dense
import keras

In [11]:
model = Sequential()
model.add(Dense(8,activation='relu',input_dim=4))
model.add(Dense(8,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


In [13]:
#model = Sequential([
#    Dense(8,activation='relu',input_shape=[4]),
#    Dense(8,activation='relu'),
#    Dense(8,activation='relu'),
#    Dense(1,activation='sigmoid')
#])

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


In [15]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [16]:
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
50/50 [==============================] - 0s 820us/step - loss: 0.6806 - accuracy: 0.5337
Epoch 2/100
50/50 [==============================] - 0s 929us/step - loss: 0.6210 - accuracy: 0.8669
Epoch 3/100
50/50 [==============================] - 0s 947us/step - loss: 0.5401 - accuracy: 0.9337
Epoch 4/100
50/50 [==============================] - 0s 868us/step - loss: 0.4139 - accuracy: 0.9619
Epoch 5/100
50/50 [==============================] - 0s 755us/step - loss: 0.2507 - accuracy: 0.9812
Epoch 6/100
50/50 [==============================] - 0s 701us/step - loss: 0.1254 - accuracy: 0.9869
Epoch 7/100
50/50 [==============================] - 0s 735us/step - loss: 0.0807 - accuracy: 0.9887
Epoch 8/100
50/50 [==============================] - 0s 878us/step - loss: 0.0667 - accuracy: 0.9875
Epoch 9/100
50/50 [==============================] - 0s 2ms/step - loss: 0.0627 - accuracy: 0.9875
Epoch 10/100
50/50 [==============================] - 0s 794us/step - loss: 0.0602 - accuracy

50/50 [==============================] - 0s 1ms/step - loss: 0.0486 - accuracy: 0.9906
Epoch 83/100
50/50 [==============================] - 0s 1ms/step - loss: 0.0483 - accuracy: 0.9906
Epoch 84/100
50/50 [==============================] - 0s 1ms/step - loss: 0.0484 - accuracy: 0.9912
Epoch 85/100
50/50 [==============================] - 0s 1ms/step - loss: 0.0483 - accuracy: 0.9887
Epoch 86/100
50/50 [==============================] - 0s 1ms/step - loss: 0.0483 - accuracy: 0.9900
Epoch 87/100
50/50 [==============================] - 0s 1ms/step - loss: 0.0484 - accuracy: 0.9900
Epoch 88/100
50/50 [==============================] - 0s 1ms/step - loss: 0.0484 - accuracy: 0.9906
Epoch 89/100
50/50 [==============================] - 0s 1ms/step - loss: 0.0482 - accuracy: 0.9900
Epoch 90/100
50/50 [==============================] - 0s 1ms/step - loss: 0.0481 - accuracy: 0.9906
Epoch 91/100
50/50 [==============================] - 0s 1ms/step - loss: 0.0485 - accuracy: 0.9887
Epoch 92/100


In [17]:
# Evaluation

In [18]:
y_pred = model.predict(X_test)

In [19]:
y_pred = y_pred.round()
y_pred

array([[0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],

In [20]:
y_test

array([0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,

In [21]:
from sklearn.metrics import confusion_matrix,classification_report

In [22]:
print(confusion_matrix(y_test,y_pred))

[[205   3]
 [  4 188]]


In [23]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.98       208
           1       0.98      0.98      0.98       192

    accuracy                           0.98       400
   macro avg       0.98      0.98      0.98       400
weighted avg       0.98      0.98      0.98       400



In [24]:
model.evaluate(X_test,y_test)

13/13 [==============================] - 0s 997us/step - loss: 0.0891 - accuracy: 0.9825


[0.08909303694963455, 0.9825000166893005]