In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification

In [2]:
X,y = make_classification(n_samples=4000,n_features=21,n_informative=4,n_classes=3,random_state=0)

In [3]:
X

array([[ 1.11618854, -0.77515272, -1.02401743, ..., -2.18550459,
        -0.01173131, -0.35948958],
       [-0.10744267, -1.18874337, -0.15944638, ..., -0.26527816,
        -0.14463475,  0.83361592],
       [-0.57364847, -0.53966181,  0.19524704, ...,  0.06998157,
         0.39895741,  0.78837482],
       ...,
       [-1.50392252, -0.0827537 ,  1.00214643, ..., -0.00549623,
        -0.10803306, -0.1808804 ],
       [ 0.68625613, -0.31703464, -0.41001729, ...,  1.61362406,
         0.54960093, -0.61350134],
       [ 0.0672496 , -1.03691542,  0.63640417, ...,  0.05555112,
        -0.18243124, -0.96500581]])

In [4]:
X.shape

(4000, 21)

In [5]:
y

array([2, 1, 1, ..., 2, 0, 1])

In [6]:
y.shape

(4000,)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [9]:
X_train.shape

(3200, 21)

In [10]:
X_test.shape

(800, 21)

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [12]:
model = Sequential()
model.add(Dense(100,activation=tf.nn.relu,input_dim=21))
model.add(Dense(100,activation=tf.nn.relu))
model.add(Dense(50,activation=tf.nn.relu))
model.add(Dense(3,activation=tf.nn.softmax))

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 100)               2200      
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 153       
Total params: 17,503
Trainable params: 17,503
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [15]:
model.fit(X_train,y_train,epochs=100)

Epoch 1/100
100/100 [==============================] - 0s 907us/step - loss: 0.6557 - accuracy: 0.7297
Epoch 2/100
100/100 [==============================] - 0s 835us/step - loss: 0.4320 - accuracy: 0.8322
Epoch 3/100
100/100 [==============================] - 0s 842us/step - loss: 0.3781 - accuracy: 0.8578
Epoch 4/100
100/100 [==============================] - 0s 947us/step - loss: 0.3506 - accuracy: 0.8606
Epoch 5/100
100/100 [==============================] - 0s 974us/step - loss: 0.3234 - accuracy: 0.8756
Epoch 6/100
100/100 [==============================] - 0s 954us/step - loss: 0.3028 - accuracy: 0.8872
Epoch 7/100
100/100 [==============================] - 0s 1ms/step - loss: 0.2983 - accuracy: 0.8863
Epoch 8/100
100/100 [==============================] - 0s 2ms/step - loss: 0.2698 - accuracy: 0.9016
Epoch 9/100
100/100 [==============================] - 0s 1ms/step - loss: 0.2484 - accuracy: 0.9112
Epoch 10/100
100/100 [==============================] - 0s 2ms/step - loss: 0.2

100/100 [==============================] - 0s 752us/step - loss: 8.0794e-05 - accuracy: 1.0000
Epoch 80/100
100/100 [==============================] - 0s 722us/step - loss: 7.6222e-05 - accuracy: 1.0000
Epoch 81/100
100/100 [==============================] - 0s 882us/step - loss: 7.1647e-05 - accuracy: 1.0000
Epoch 82/100
100/100 [==============================] - 0s 1ms/step - loss: 6.6627e-05 - accuracy: 1.0000
Epoch 83/100
100/100 [==============================] - 0s 1ms/step - loss: 6.1273e-05 - accuracy: 1.0000
Epoch 84/100
100/100 [==============================] - 0s 1ms/step - loss: 5.8125e-05 - accuracy: 1.0000
Epoch 85/100
100/100 [==============================] - 0s 748us/step - loss: 5.4381e-05 - accuracy: 1.0000
Epoch 86/100
100/100 [==============================] - 0s 735us/step - loss: 5.0784e-05 - accuracy: 1.0000
Epoch 87/100
100/100 [==============================] - 0s 739us/step - loss: 4.7660e-05 - accuracy: 1.0000
Epoch 88/100
100/100 [=========================

In [16]:
y_pred = model.predict(X_test)

In [17]:
y_pred.round()

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [18]:
y_pred = np.argmax(y_pred,axis=1)

In [19]:
y_pred

array([2, 2, 1, 1, 0, 1, 2, 0, 1, 1, 1, 1, 0, 0, 2, 1, 2, 2, 0, 1, 1, 1,
       1, 2, 1, 0, 0, 2, 0, 0, 1, 2, 1, 1, 1, 2, 2, 0, 2, 2, 1, 0, 2, 1,
       2, 2, 1, 0, 2, 2, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 2, 1, 2, 1, 0, 2,
       0, 1, 0, 0, 0, 2, 2, 2, 0, 0, 1, 1, 1, 2, 1, 1, 0, 0, 2, 2, 2, 1,
       2, 1, 1, 0, 0, 0, 0, 2, 0, 2, 2, 2, 1, 0, 2, 1, 1, 1, 1, 2, 1, 1,
       0, 1, 2, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 0, 2, 0, 2, 1, 2, 0, 0, 2,
       2, 1, 2, 0, 2, 1, 2, 2, 1, 0, 2, 2, 1, 1, 2, 2, 2, 1, 0, 0, 1, 1,
       0, 0, 2, 1, 1, 2, 0, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 0, 2, 2, 1, 0,
       1, 0, 0, 1, 2, 1, 1, 2, 0, 0, 0, 2, 1, 1, 2, 2, 1, 1, 1, 2, 1, 0,
       0, 0, 2, 2, 0, 0, 1, 1, 0, 0, 2, 1, 0, 2, 1, 0, 2, 1, 2, 0, 1, 0,
       2, 0, 0, 0, 2, 2, 2, 1, 2, 1, 2, 1, 0, 1, 0, 0, 2, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 2, 2, 0, 0, 1, 0, 2, 1, 1, 0,
       0, 1, 2, 0, 2, 1, 1, 0, 1, 1, 2, 1, 1, 0, 0, 2, 0, 1, 1, 1, 2, 0,
       1, 0, 2, 1, 0, 1, 1, 1, 2, 2, 2, 0, 1, 0, 0,

In [20]:
model.evaluate(X_test,y_test)

25/25 [==============================] - 0s 908us/step - loss: 1.9785 - accuracy: 0.7950


[1.9784512519836426, 0.7950000166893005]

In [21]:
from sklearn.metrics import confusion_matrix,classification_report

In [22]:
print(confusion_matrix(y_test,y_pred))

[[220  19  28]
 [ 21 206  23]
 [ 33  40 210]]


In [ ]:
print(classification_report(y_test,y_pred))