In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('iris.csv',names=['sep_l','sep_w','pet_l','pet_w','label'])

In [3]:
dataset

sep_l  sep_w  pet_l  pet_w           label
0      5.1    3.5    1.4    0.2     Iris-setosa
1      4.9    3.0    1.4    0.2     Iris-setosa
2      4.7    3.2    1.3    0.2     Iris-setosa
3      4.6    3.1    1.5    0.2     Iris-setosa
4      5.0    3.6    1.4    0.2     Iris-setosa
..     ...    ...    ...    ...             ...
145    6.7    3.0    5.2    2.3  Iris-virginica
146    6.3    2.5    5.0    1.9  Iris-virginica
147    6.5    3.0    5.2    2.0  Iris-virginica
148    6.2    3.4    5.4    2.3  Iris-virginica
149    5.9    3.0    5.1    1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
X = dataset.iloc[:,0:4].values

In [5]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
y = dataset.iloc[:,[4]].values

In [7]:
y

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

In [8]:
y.shape

(150, 1)

In [9]:
from sklearn.preprocessing import OneHotEncoder

In [10]:
ohe = OneHotEncoder(sparse=False)

In [11]:
y = ohe.fit_transform(y)

In [12]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [15]:
X_train.shape

(120, 4)

In [16]:
X_test.shape

(30, 4)

In [17]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [18]:
model = Sequential([
    Dense(8,activation='relu',input_shape=[4]),
    Dense(8,activation='relu'),
    Dense(8,activation='relu'),
    Dense(3,activation='softmax')
])

In [19]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [21]:
model.fit(X_train,y_train,epochs=200)

Epoch 1/200
4/4 [==============================] - 1s 3ms/step - loss: 2.2181 - accuracy: 0.3250
Epoch 2/200
4/4 [==============================] - 0s 3ms/step - loss: 2.0410 - accuracy: 0.3250
Epoch 3/200
4/4 [==============================] - 0s 3ms/step - loss: 1.8807 - accuracy: 0.3250
Epoch 4/200
4/4 [==============================] - 0s 3ms/step - loss: 1.7350 - accuracy: 0.3250
Epoch 5/200
4/4 [==============================] - 0s 3ms/step - loss: 1.6079 - accuracy: 0.3250
Epoch 6/200
4/4 [==============================] - 0s 3ms/step - loss: 1.4935 - accuracy: 0.3250
Epoch 7/200
4/4 [==============================] - 0s 3ms/step - loss: 1.3968 - accuracy: 0.3250
Epoch 8/200
4/4 [==============================] - 0s 3ms/step - loss: 1.3156 - accuracy: 0.3250
Epoch 9/200
4/4 [==============================] - 0s 3ms/step - loss: 1.2444 - accuracy: 0.3250
Epoch 10/200
4/4 [==============================] - 0s 3ms/step - loss: 1.1796 - accuracy: 0.3250
Epoch 11/200
4/4 [===========

4/4 [==============================] - 0s 4ms/step - loss: 0.4787 - accuracy: 0.7750
Epoch 85/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4717 - accuracy: 0.8000
Epoch 86/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4653 - accuracy: 0.8167
Epoch 87/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4582 - accuracy: 0.8250
Epoch 88/200
4/4 [==============================] - 0s 4ms/step - loss: 0.4516 - accuracy: 0.8250
Epoch 89/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4445 - accuracy: 0.8333
Epoch 90/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4379 - accuracy: 0.8333
Epoch 91/200
4/4 [==============================] - 0s 4ms/step - loss: 0.4311 - accuracy: 0.8583
Epoch 92/200
4/4 [==============================] - 0s 7ms/step - loss: 0.4245 - accuracy: 0.8500
Epoch 93/200
4/4 [==============================] - 0s 3ms/step - loss: 0.4175 - accuracy: 0.8583
Epoch 94/200
4/4 [===============

4/4 [==============================] - 0s 3ms/step - loss: 0.1192 - accuracy: 0.9750
Epoch 168/200
4/4 [==============================] - 0s 3ms/step - loss: 0.1219 - accuracy: 0.9583
Epoch 169/200
4/4 [==============================] - 0s 3ms/step - loss: 0.1175 - accuracy: 0.9750
Epoch 170/200
4/4 [==============================] - 0s 3ms/step - loss: 0.1164 - accuracy: 0.9750
Epoch 171/200
4/4 [==============================] - 0s 3ms/step - loss: 0.1160 - accuracy: 0.9750
Epoch 172/200
4/4 [==============================] - 0s 3ms/step - loss: 0.1145 - accuracy: 0.9667
Epoch 173/200
4/4 [==============================] - 0s 3ms/step - loss: 0.1141 - accuracy: 0.9750
Epoch 174/200
4/4 [==============================] - 0s 3ms/step - loss: 0.1125 - accuracy: 0.9750
Epoch 175/200
4/4 [==============================] - 0s 3ms/step - loss: 0.1121 - accuracy: 0.9750
Epoch 176/200
4/4 [==============================] - 0s 3ms/step - loss: 0.1127 - accuracy: 0.9750
Epoch 177/200
4/4 [=====

In [22]:
y_pred = model.predict(X_test)

In [23]:
y_pred.round()

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], dtype=float32)

In [24]:
y_pred = np.argmax(y_pred,axis=1)

In [25]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [26]:
y_test = np.argmax(y_test,axis=1)

In [27]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [28]:
from sklearn.metrics import confusion_matrix,classification_report

In [29]:
print(confusion_matrix(y_test,y_pred))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         6

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

